#!/usr/bin/env bash

find_prime_factors() {
  local num="$1"
  if [ $((num % 2)) -eq 0 ]; then
    echo "2"
    num=$((num / 2))
  fi
  for ((i=3; i<=sqrt; i+=2)); do
    while [ $((num % i)) -eq 0 ]; do
      echo "$i"
      num=$((num / i))
    done
  done
  if [ $num -gt 2 ]; then
    if is_prime "$num"; then
      echo "$num"
    else
      for ((i=num-2; i>2; i-=2)); do
        if is_prime "$i"; then
          echo "$i"
          break
        fi
      done
    fi
  fi
}

is_prime() {
  local num="$1"
  if [ $num -lt 2 ]; then
    return 1
  fi
  if [ $((num % 2)) -eq 0 ]; then
    return 1
  fi
  for ((i=3; i<=sqrt; i+=2)); do
    if [ $((num % i)) -eq 0 ]; then
      return 1
    fi
  done
  return 0
}

if [ $# -ne 1 ]
then
  echo 'Usage: rsa <file>'
  exit 1
else
  num=$(head -n 1 "$1")
  sqrt=$((num ** 0.5))
  prime_factors=$(find_prime_factors "$num")
  echo "The prime factors of $num are: $prime_factors"
fi
