#!/usr/bin/env bash
#is a challenge

find_factors() {
  local num="$1"
  if [ $((num % 2)) -eq 0 ]; then
    echo "2"
    num=$((num / 2))
  fi
  for ((i=3; i<=sqrt; i+=2)); do
    while [ $((num % i)) -eq 0 ]; do
      echo "$i"
      num=$((num / i))
    done
  done
  if [ $num -gt 2 ]; then
    echo "$num"
  fi
}

if [ $# -ne 1 ]
then
  echo 'Usage: rsa <file>'
  exit 1
else
  num=$(head -n 1 "$1")
  sqrt=$(echo "sqrt($num)" | bc -l | awk '{print int($1+0.5)}')
  factors=$(find_factors "$num")
  echo "The factors of $num are: $factors"
fi
