#!/usr/bin/env bash
#is a challenge

find_prime_factors() {
  local num="$1"
  local factors=$(factor "$num")
  echo "The prime factors of $num are: $factors"
}

if [ $# -ne 1 ]
then
  echo 'Usage: rsa <file>'
  exit 1
else
  num=$(head -n 1 "$1")
  find_prime_factors "$num"
fi
